### ISSUE TITLE
target: FreeBSD support

### ISSUE THREAD

**Issue by EduardoRFS** [EduardoRFS/reason-mobile#7]
Currently only `freebsd.x86_64` is implemented and only from Linux x86_64

## TODO

- [ ] macOS -> freebsd.x86_64
- [ ] Linux x86_64 -> freebsd.arm64
- [ ] Linux ARM64 -> freebsd.arm64
- [ ] macOS -> freebsd.arm64
